### ISSUE TITLE
Demo page error: Fatal error: Cannot retrieve a version for package rector/rector since it is replaced by some other package

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/getrector.org#293] opened 2021-03-20 14:38 UTC
Step to reproduce:

Open https://getrector.org/demo/6bb1f170-57b0-4fb1-8e53-7fbaa57fb736 click "Process", got the following error:

![Screen Shot 2021-03-20 at 21 37 42](https://user-images.githubusercontent.com/459648/111873751-8a311580-89c4-11eb-9aa3-50dda1c19e29.png)

**Comment by TomasVotruba** [comment] 2021-03-20 14:55
Thanks! 

Any steps how to reproduce locally with repository only? That way I could try to figure out the solution

**Comment by samsonasik** [comment] 2021-03-20 15:05
I tried install via clone - run composer update, got the following error:

```bash
An exception has been thrown during the rendering of a template ("Asset manifest file "/Users/samsonasik/www/getrector.org/public/build/manifest.json" does not exist.").
```

it seems need docker

**Comment by JanMikes** [comment] 2021-03-20 16:58
Hi, this bug is caused by https://github.com/rectorphp/getrector.org/pull/292

I will create integration test as this is happening way too often and finally when demo does not need to run in docker it will be much easier.

You do not need docker to run getrector.org locally, just follow the instructions that are happening in docker build:
```
yarn install
yarn run build
composer install
```

**Comment by TomasVotruba** [comment] 2021-03-20 17:46
Thank you Honza

**Comment by JanMikes** [comment] 2021-03-20 17:51
I also found this issue:
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
```

**Comment by JanMikes** [comment] 2021-03-20 17:53
https://github.com/rectorphp/getrector.org/runs/2156349807?check_suite_focus=true

Test successfully detects this issue

**Comment by JanMikes** [comment] 2021-03-20 18:02
Im not sure how to fix. I merged the failing test into main (as the broken code is already merged) so you can rebase and fix.

I am able to get to it later today (in like 3 hours) if you are not able to fix yourself. 

Anyways it seems like some changes in rector itself are causing this and are not related to getrector.org at all. Just try to install rector locally and run with json output formatter.

**Comment by TomasVotruba** [comment] 2021-03-20 18:21
Thank you :+1: 

It's related to `jean85/pretty-package-versions`. It kinda buggy with various composer 1/2 prefixed combinations.

**Closed** 2021-03-20 18:44 UTC
